### ISSUE TITLE
Building error with libcriterion.dylib

### ISSUE THREAD

**Issue by daparpon** [Snaipe/Criterion#234] opened 2018-01-12 11:43 UTC
Hi! I have been trying to install Criterion in my macOS Sierra, but I always get the same error that stops the process (either with the package Homebrew distribution or directly cloning and compiling the repository). This is the trace:

veraw140-229:build elp$ cmake --build .
[  2%] Built target git2-dependency
[  4%] Built target dyncall_s-dependency
[  7%] Built target nanomsg-dependency
[  7%] Built target csptr-dependency
[  9%] Built target boxfort-dependency
[ 12%] Linking C shared library libcriterion.dylib
Undefined symbols for architecture x86_64:
  "_libintl_bindtextdomain", referenced from:
      _init_i18n in i18n.c.o
  "_libintl_dgettext", referenced from:
      _criterion_run_all_tests_impl in runner.c.o
      _run_test in runner_coroutine.c.o
      _process_all_output in output.c.o
      _criterion_log_noformat in logging.c.o
      _criterion_plog in logging.c.o
      _normal_log_pre_all in normal.c.o
      _normal_log_pre_init in normal.c.o
      ...
  "_libintl_dngettext", referenced from:
      _normal_log_pre_suite in normal.c.o
  "_libintl_setlocale", referenced from:
      _criterion_handle_args in params.c.o
  "_libintl_textdomain", referenced from:
      _criterion_handle_args in params.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcriterion.3.1.0.dylib] Error 1
make[1]: *** [CMakeFiles/criterion.dir/all] Error 2
make: *** [all] Error 2

As far as I know, it somehow always looks for the libintl library files installed by Homebrew in /usr/local/Cellar/gettext (if the folder is deleted, the installation script is not able to find libintl.h anymore), but I have reinstalled and relinked gettext and the error keeps happening. How could I solve it?

Thanks in advance and sorry for the inconviniencies.

**Comment by Snaipe** [comment] 2018-01-12 13:14
I'm guessing there's a bug in the build system where libintl isn't linked even though it's found (maybe it things it's in the libc?)

If you don't care about internationalization, you can just disable it entirely by passing -DI18N=OFF to cmake.

Could you attach your CMakeCache.txt, CMakeFiles/CMakeOutput.log and CMakeFiles/CMakeError.log in this issue?

**Comment by MrAnno** [comment] 2018-06-01 19:06
Hi @Snaipe,

I have the same problem on macOS High Sierra.

You can find my `CMakeCache.txt`, `CMakeFiles/CMakeOutput.log` and `CMakeFiles/CMakeError.log` [here](https://gist.github.com/MrAnno/2080a10c770c7fbb3e544e272a1c442c).

I've built the bleeding branch, but both v2.3.1 and v2.3.2 have the same libintl linking issue.

It seems, `LIBINTL_LIBRARIES` is intentionally left empty because of the existence of`dgettext()`:
https://github.com/Snaipe/Criterion/blob/48d83b8d9b51825f23adab1eb3773a2ed383cfd5/.cmake/Modules/FindLibintl.cmake#L40-L44

I don't fully understand the idea behind this check.

**Comment by apthorpe** [comment] 2020-07-22 19:46
@Snaipe Thanks for the `-DI18N=OFF` tip; that may solve my immediate issue. Otherwise, I'm seeing the same behavior with v2.3.3 under El Capitan (10.11.8) using fink for package management (`brew` doesn't support older OS versions and I've only had luck with fink).

Anyway, `libgettext8-dev` and `-shlibs` are installed and `libintl.h` is confirmed to be under `/opt/sw/include`

I've resolved similar dependency issues by passing `-DCMAKE_PREFIX_PATH:PATH=/opt/sw` to CMake during configuration but it doesn't seem to be helping in this case. Not sure if it's relevant, but I'm building Criterion using `ExternalProject_Add` within my own CMake project and it's working under Windows, just crapping out on OSX due to not finding `/opt/sw/include/libintl.h`. I'm more than happy to send along info if you think it'll help but I also completely understand if this is too weird of an edge case to address (old OS, subproject build, *etc.*)

**Comment by Snaipe** [comment] 2022-01-01 13:44
Closing this as we're not even using CMake anymore. If the issue still exists with meson, let's open a new issue about this and fix it there.

**Closed by Snaipe** 2022-01-01 13:44 UTC
Labels: Unconfirmed, Needs Update
