### ISSUE TITLE
Criterion tests are being removed by LTO

### ISSUE THREAD

**Issue by fdelbos** [Snaipe/Criterion#436] opened 2022-03-24 09:32 UTC
Hi, when i m building my tests everything looks fine but when i run Criterion, it does not run any test...

building phase:
```
[ 70%] Building C object CMakeFiles/tests.dir/src/test/lib/common/buffer.c.o
/usr/bin/cc  -I/home/fred/dev/xxx/src/ext/criterion-2.4.0/include -I/home/fred/dev/xxx/src/inc -I/home/fred/dev/xxx/x86/src/inc  -flto -fno-fat-lto-objects -fPIE   -std=gnu11 -O3 -DUNIX -D_GNU_SOURCE -Wall -Wpedantic -Wextra -Wshadow -Wstrict-overflow -fno-strict-aliasing -Werror -D_SYSTEM_X86_64_ -pthread -o CMakeFiles/tests.dir/src/test/lib/common/buffer.c.o   -c /home/fred/dev/xxx/src/test/lib/common/buffer.c
[ 80%] Building C object CMakeFiles/tests.dir/src/test/lib/common/utils.c.o
/usr/bin/cc  -I/home/fred/dev/xxx/src/ext/criterion-2.4.0/include -I/home/fred/dev/xxx/src/inc -I/home/fred/dev/xxx/x86/src/inc  -flto -fno-fat-lto-objects -fPIE   -std=gnu11 -O3 -DUNIX -D_GNU_SOURCE -Wall -Wpedantic -Wextra -Wshadow -Wstrict-overflow -fno-strict-aliasing -Werror -D_SYSTEM_X86_64_ -pthread -o CMakeFiles/tests.dir/src/test/lib/common/utils.c.o   -c /home/fred/dev/xxx/src/test/lib/common/utils.c
[ 90%] Building C object CMakeFiles/tests.dir/src/test/lib/crc/crc.c.o
/usr/bin/cc  -I/home/fred/dev/xxx/src/ext/criterion-2.4.0/include -I/home/fred/dev/xxx/src/inc -I/home/fred/dev/xxx/x86/src/inc  -flto -fno-fat-lto-objects -fPIE   -std=gnu11 -O3 -DUNIX -D_GNU_SOURCE -Wall -Wpedantic -Wextra -Wshadow -Wstrict-overflow -fno-strict-aliasing -Werror -D_SYSTEM_X86_64_ -pthread -o CMakeFiles/tests.dir/src/test/lib/crc/crc.c.o   -c /home/fred/dev/xxx/src/test/lib/crc/crc.c
[100%] Linking C executable tests
/usr/bin/cmake -E cmake_link_script CMakeFiles/tests.dir/link.txt --verbose=1
/usr/bin/cc -flto -fno-fat-lto-objects   CMakeFiles/tests.dir/src/test/lib/common/buffer.c.o CMakeFiles/tests.dir/src/test/lib/common/utils.c.o CMakeFiles/tests.dir/src/test/lib/crc/crc.c.o  -o tests   -L/home/fred/dev/xxx/src/ext/criterion-2.4.0/lib  -Wl,-rpath,/home/fred/dev/xxx/src/ext/criterion-2.4.0/lib -lcriterion libcommon.a libcrc.a -pthread
make[3]: Leaving directory '/home/fred/dev/xxx/x86'
[100%] Built target tests

```

then when i run it, there is 0 tests
```
./tests
[====] Synthesis: Tested: 0 | Passing: 0 | Failing: 0 | Crashing: 0
```

Some of the tests i know are good because they use to run and pass before...

**Comment by fdelbos** [comment] 2022-03-24 09:38
Ok i. found what's was wrong, if i remove theses flags:
```
-flto -fno-fat-lto-objects
```

Criterion does not support lto...

**Comment by Snaipe** [comment] 2022-03-24 09:47
To be more precise, your code under test can have link-time optimization performed on it, but the test executable probably shouldn't, because it's likely that the test functions will be marked as dead code and removed. After all, nothing directly references them, and they're discovered at runtime.

I'd be nice if there was a way to mark these functions as used/unremovable but I'm not sure there a combination of flags to achieve this.

**Comment by Snaipe** [comment] 2022-03-24 09:56
By chance, if you were to apply this patch to include/criterion/internal/test.h, does this fix the issue with -lto?

```diff
diff --git a/include/criterion/internal/test.h b/include/criterion/internal/test.h
index e299ca6..afe2150 100644
--- a/include/criterion/internal/test.h
+++ b/include/criterion/internal/test.h
@@ -174,6 +174,7 @@ static const char *const cr_msg_test_fini_other_exception = "Caught some unexpec
         &CR_IDENTIFIER_(Category, Name,  extra)                              \
     };                                                                       \
     CR_SECTION_("cr_tst")                                                    \
+    CR_API                                                                   \
     struct criterion_test *CR_IDENTIFIER_(Category, Name, ptr)               \
         = &CR_IDENTIFIER_(Category, Name, meta) CR_SECTION_SUFFIX_;          \
     CR_TEST_PROTOTYPE_(Category, Name)
@@ -190,6 +191,7 @@ static const char *const cr_msg_test_fini_other_exception = "Caught some unexpec
         &CR_SUITE_IDENTIFIER_(Name, extra),                              \
     };                                                                   \
     CR_SECTION_("cr_sts")                                                \
+    CR_API                                                               \
     struct criterion_suite *CR_SUITE_IDENTIFIER_(Name, ptr)              \
         = &CR_SUITE_IDENTIFIER_(Name, meta) CR_SECTION_SUFFIX_
```

This essentially forces the test and suite definitions to become exported, which is usually fairly uncommon for executables, but might actually cause LTO to not remove them.

**Comment by fdelbos** [comment] 2022-03-24 10:48
Hi Snaipe! I tried your patch and it didn't fixed it... But i think this is fine not to have LTO in tests. Maybe just a warning in the docs would save peoples time ?

**Comment by Snaipe** [comment] 2022-04-13 16:37
I was able to reproduce it with just `-flto -O1`. #443 fixes it on my end, can you check that it does indeed fix it on your end too?

**Closed** 2022-04-13 17:23 UTC
Labels: Bug, Normal, API
