### ISSUE TITLE
Test statistics seem to be incorrect sometimes

### ISSUE THREAD

**Issue by bturrubiates** [Snaipe/Criterion#15] opened 2015-04-10 18:16 UTC
Not sure if this is expected behavior, but upon failures I'll get output of this sort: 

```
[====] Synthesis: Tested: 12 | Passing: 0 | Failing: 13 | Crashing: 5 
```

The failing number is larger than the number of tests listed as "Tested". (I can confirm there are only 12)

This also seems to comes up when using the .disabled option. The "Tested" stat will be the full number, but the sum of passing and failing will approximate the correct number of tests actually run (non-disabled).

**Comment by Snaipe** [comment] 2015-04-10 20:06
I cannot seem to reproduce the issue, could you provide a sample where you do get this behaviour ?
Also, what system are you on ?

**Comment by bturrubiates** [comment] 2015-04-10 20:15
The test in specific that produced these results can be found [here](https://github.com/ofi-cray/libfabric-cray/blob/master/prov/gni/test/cq.c). 

The machine I'm using is [Edison](https://www.nersc.gov/users/computational-systems/edison/configuration/) at NERSC. 

Unfortunately, you won't be able to run this test since it has hardware/software requirements that are strange. I'll see if I can create a test to reproduce it more simply.

**Comment by bturrubiates** [comment] 2015-04-10 20:22
A quick example of the disabled thing: 
```
#include <criterion/criterion.h>

TestSuite(whatever, .disabled = true);

Test(whatever, 1)
{
        assert(0);
}

Test(whatever, 2)
{
        assert(0);
}

Test(whatever, 3)
{
        assert(0);
}

Test(whatever, 4)
{
        assert(0);
}

Test(whatever, 5)
{
        assert(0);
}

Test(enabled, 1)
{
        assert(1);
}
```
And the output: 
```
[====] Synthesis: Tested: 6 | Passing: 1 | Failing: 0 | Crashing: 0
```

I would think "Tested" should be 1.

**Comment by Snaipe** [comment] 2015-04-10 20:50
So it should.

Also, by any chance, is the teardown crashing in one of your tests ? It seems to be the only logical explanation to the higher failing number (test gets reported as a failure, then crashed in the teardown, and the crash gets reported).

**Comment by bturrubiates** [comment] 2015-04-10 20:50
I don't know if this would help, but it seems it's the test suite 'creation' that is causing this: 
```
[----] Criterion v1.1.0
[====] Running 3 tests from cq_msg:
[SKIP] cq_msg::single: Test is disabled
[SKIP] cq_msg::multi_read: Test is disabled
[SKIP] cq_msg::fill: Test is disabled
[====] Running 5 tests from creation:
[RUN ] creation::format_context
[----] ../prov/gni/test/cq.c:167: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_entry)
[====] creation::format_context: (0.00s)
[RUN ] creation::format_data
[----] ../prov/gni/test/cq.c:193: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_data_entry)
[====] creation::format_data: (0.00s)
[RUN ] creation::format_msg
[----] ../prov/gni/test/cq.c:180: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_msg_entry)
[====] creation::format_msg: (0.00s)
[RUN ] creation::format_tagged
[----] ../prov/gni/test/cq.c:206: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_tagged_entry)
[====] creation::format_tagged: (0.00s)
[RUN ] creation::format_unspec
[----] ../prov/gni/test/cq.c:151: Assertion failed: fi_cq_open
[====] creation::format_unspec: (0.00s)
[----] ../prov/gni/test/cq.c:151: Unexpected signal caught below this line!
[====] creation::format_unspec: CRASH!
[====] Running 2 tests from insertion:
[SKIP] insertion::single: Test is disabled
[SKIP] insertion::limit: Test is disabled
[====] Running 2 tests from reading:
[SKIP] reading::error: Test is disabled
[SKIP] reading::empty: Test is disabled
[====] Synthesis: Tested: 12 | Passing: 0 | Failing: 6 | Crashing: 1
```
Notice that failing is 6. I'm not really sure why...
I would expect: Tested: 5 | Passing: 0 | Failing: 5 | Crashing 1

Although if I include the fix that makes those tests pass then it counts them correctly (with the exception of the Tested stat):
```
[----] Criterion v1.1.0
[====] Running 3 tests from cq_msg:
[SKIP] cq_msg::single: Test is disabled
[SKIP] cq_msg::multi_read: Test is disabled
[SKIP] cq_msg::fill: Test is disabled
[====] Running 5 tests from creation:
[RUN ] creation::format_context
[PASS] creation::format_context: (0.00s)
[RUN ] creation::format_data
[PASS] creation::format_data: (0.00s)
[RUN ] creation::format_msg
[PASS] creation::format_msg: (0.00s)
[RUN ] creation::format_tagged
[PASS] creation::format_tagged: (0.00s)
[RUN ] creation::format_unspec
[PASS] creation::format_unspec: (0.00s)
[====] Running 2 tests from insertion:
[SKIP] insertion::single: Test is disabled
[SKIP] insertion::limit: Test is disabled
[====] Running 2 tests from reading:
[SKIP] reading::error: Test is disabled
[SKIP] reading::empty: Test is disabled
[====] Synthesis: Tested: 12 | Passing: 5 | Failing: 0 | Crashing: 0
```

**Comment by bturrubiates** [comment] 2015-04-10 20:53
Okay, I disabled teardown for the creation test suite and you're correct! 
```
[----] Criterion v1.1.0
[====] Running 3 tests from cq_msg:
[SKIP] cq_msg::single: Test is disabled
[SKIP] cq_msg::multi_read: Test is disabled
[SKIP] cq_msg::fill: Test is disabled
[====] Running 5 tests from creation:
[RUN ] creation::format_context
[----] ../prov/gni/test/cq.c:167: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_entry)
[====] creation::format_context: (0.00s)
[RUN ] creation::format_data
[----] ../prov/gni/test/cq.c:193: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_data_entry)
[====] creation::format_data: (0.00s)
[RUN ] creation::format_msg
[----] ../prov/gni/test/cq.c:180: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_msg_entry)
[====] creation::format_msg: (0.00s)
[RUN ] creation::format_tagged
[----] ../prov/gni/test/cq.c:206: Assertion failed: cq_priv->entry_size == sizeof(struct fi_cq_tagged_entry)
[====] creation::format_tagged: (0.00s)
[RUN ] creation::format_unspec
[----] ../prov/gni/test/cq.c:151: Assertion failed: fi_cq_open
[====] creation::format_unspec: (0.00s)
[====] Running 2 tests from insertion:
[SKIP] insertion::single: Test is disabled
[SKIP] insertion::limit: Test is disabled
[====] Running 2 tests from reading:
[SKIP] reading::error: Test is disabled
[SKIP] reading::empty: Test is disabled
[====] Synthesis: Tested: 12 | Passing: 0 | Failing: 5 | Crashing: 0
```
That did result in the correct amount failing. So now the question is whether or not the setup/teardown should affect the failing number.

**Comment by bturrubiates** [comment] 2015-04-10 20:59
Sorry, I was aware that it was most likely crashing in the teardown because the bug in specific that's causing this to catastrophically fail also results in undefined behavior in the teardown which could seg fault. In retrospect it was probably obvious, but I wasn't expecting the teardown/setup phase to change the outcome of the stats.

**Comment by Snaipe** [comment] 2015-04-10 21:23
Both issues should be fixed now. Please let me know if you still experience any bugs :)

**Comment by bturrubiates** [comment] 2015-04-10 21:48
Just tested and can confirm that the output is correct now! Thanks

**Closed** 2015-04-10 21:50 UTC
Labels: bug
