### ISSUE TITLE
cr_assert* extremely slow

### ISSUE THREAD

**Issue by fserra** [Snaipe/Criterion#172] opened 2016-10-22 06:53 UTC
Hi  
When running the following test

``` C
  #include <stdio.h>
  #include <criterion/criterion.h> 

  Test(looping, test)
  {
     int len = 450;
     int i, j;

     /* loop 1 */
     for( i = 0; i < len; ++i )
     {      
        /* loop 2 */
        for( j = 0; j < i; ++j )
        {
           cr_assert(j < i);
        }
     }
  }
```

It takes

```
real    0m13.019s
user    0m4.524s
sys 0m10.388s
```

If I replace `cr_assert` with a normal assert, it takes

```
real    0m0.009s
user    0m0.004s
sys 0m0.000s
```

Any ideas what is going on?

**Comment by fserra** [comment] 2016-10-22 06:57
I am using
```
>> gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
```

**Comment by fserra** [comment] 2016-10-22 07:41
with v2.2.2 I get
```
real	0m0.144s
user	0m0.132s
sys	0m0.124s
```
so something happen in between

**Comment by Snaipe** [comment] 2016-10-22 08:09
This is definitely a result of both having a protocol layer and using nanomsg. I'll do some profiling on the sending function to see what's up.

This is also a side-effect of having to build statistics for each assert (even when they passed), so this is quite taxing. Skipping passing sends for the future could be a nice touch (along with perhaps a `--full-statistics` to fallback to the old model)

**Comment by stv0g** [comment] 2016-10-30 23:04
I work around this, by moving `cr_asser_*` calls out of my tight loops. But this is not a nice solution..

Do we always need nanomsg / IPC? I don't see the need in a non-forking process..

**Comment by Snaipe** [comment] 2016-10-30 23:54
All tests must be fork'ed/exec'ed -- the runner cannot hold the guarantees criterion makes in its API (timeouts, quotas, exit status test, and crash test) without that; so IPC is always required in some form.

A better long term solution would be to stop sending data when assertions are passing, and make a coalesced message of all passed assertions at the end of the test instead.

**Comment by kugel-** [comment] 2017-01-05 07:56
Is there going to be a fix or workaround for 2.3.0? I think we'll continue with the 2.2.x series otherwise (2.3.0 doesn't bring a benefit for us as far is I can see).

**Comment by Snaipe** [comment] 2017-01-05 12:06
Yes, this is a regression, and yes, this is going to be addressed in 2.3.1. The slowdown is a consequence of the fix for #82, which was a red herring on the i/o structure of criterion 2.2, so unless you have tests with enough assertions to fill the pipe buffer, you can live without it.

**Comment by kugel-** [comment] 2017-01-05 12:17
Good to hear. We haven't been bitten by #82 yet but we do have tests that become extremely slow with 2.3.0

**Comment by Snaipe** [comment] 2017-01-18 18:12
I've done some profiling on criterion, and I noticed a few interesting things:

First, there was a huge slowdown for the above case due to `cri_sections_getaddr` -- it turns out that the fix for #91 made performance for tests with a large number of assertions drop down because section limits were retrieved repeatedly. I've commited a fix to address this by caching the limits before PRE_ALL, and the performance increased threefold, going from 15 seconds of execution time to 5 seconds.

Secondly, the other source of the slowdown mostly comes from nanopb's `pb_decode`. I think this comes from the library allocating a lot of dynamic fields, but I'm not sure yet.
I think this slowdown might be justified because the complexity of the protocol has gone up, and we're basically trading off performance for correctness.

I'll see if I can perhaps find a way to use a custom allocator with nanopb to favor the reuse of common fields, but the best bet in the long run might be to just limit the statistics sent to the runner, as mentionned above, since most users only care about the details of failed assertions, not the ones that succeeded.

**Closed** 2017-01-20 17:06 UTC
Labels: Bug, Minor, Runtime

**Comment by kugel-** [comment] 2019-11-13 15:12
Is it possible that cr_expect_* is still affected by this?

**Comment by Snaipe** [comment] 2019-11-13 20:26
Both expect and assert use the same underlying API, so it shouldn't be affected. If you've got a large number of failing excepts you'll still find poor performance since we're sending protobuf messages down the wire.

Re-reading this thread, I think there's still room for improvement. Most notably, the decoding of a message really ought to be performing better. I'll open a new issue to document that.

**Comment by kugel-** [comment] 2019-11-13 21:29
Hey, if you found another low-hanging fruit then my false report was worth it :-)

The background of my question was that I'm seeing strange behavior for some of our tests when they run inside Jenkins jobs. Some of the tests really take ages (3+ minutes) to complete, and the random sample I looked at uses cr_expect_*, and then a quick hack to use cr_assert_* in the worst-performing one brought it down to <1s.

However, after a few more tests it looks like the Jenkins environment is somehow busted. I don't know why but some tests fail for strange reasons, others take ages, and then there is also a large delay that is not cause by the tests (junit reported sum of times is way below the total duration of the job).

It does look like to me that Jenkins is somehow throttling the test runs, perhaps when they do some syscall (does the worker <-> runner communication involve a syscall?)
