### ISSUE TITLE
Tests fork-bombing system when compiling with clang 5.0.1

### ISSUE THREAD

**Issue by lodi-g** [Snaipe/Criterion#247] opened 2018-02-19 17:15 UTC
Code snippet:

```c
#include <criterion/criterion.h>
Test(test, test) {}
```

When compiling with gcc it works fine:
```sh
╰─ gcc test.c -lcriterion && ./a.out
[====] Synthesis: Tested: 1 | Passing: 1 | Failing: 0 | Crashing: 0 
```

When compiling with clang it loops infintely and fails to run any test:
```sh
╰─ clang test.c -lcriterion && ./a.out
criterion: Could not spawn test instance: Too many open files
criterion: Could not spawn test instance: Protocol error
criterion: Could not spawn test instance: Protocol error
criterion: Could not spawn test instance: Protocol error
criterion: Could not spawn test instance: Protocol error
criterion: Could not spawn test instance: Protocol error
[...]
```

GCC version: 7.3.0
Clang version: 5.0.1

System: `Linux arch 4.15.3-2-ARCH #1 SMP PREEMPT Thu Feb 15 00:13:49 UTC 2018 x86_64 GNU/Linux`

Thank you

**Comment by lodi-g** [comment] 2018-03-13 15:26
It seems to be working when compiling with a MBP:

```
$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.39.2)
[...]
```

**Comment by am11** [comment] 2018-03-13 20:10
Hi, I tested the example with clang 5.0.1 on Ubuntu and Alpine Linux, and couldn't reproduce the described error. On Alpine, however, I built with latest `bleeding` branch, and it crashed due to another error:

```ash
/ # clang test.c -lcriterion && ./a.out
[----] Warning! The test `test::test` exited during its setup or teardown.
[====] Synthesis: Tested: 0 | Passing: 0 | Failing: 1 | Crashing: 1
```

Could you check the output of `ulimit -n`?  I would try increasing it so:

```sh
echo "current ulimit is: `ulimit -n`..."
ulimit -n 1024 # value is in bytes; on Alpine I have 1024KBs => 1048576. you can try increasing it in Arch
echo "new limit: `ulimit -n`"
```

**Comment by lodi-g** [comment] 2018-03-13 20:42
Hi,

It's still doing the same here. My limit was already set at 1024.
It seems to be a Arch-related issue? What's your clang version?

Thank you

**Comment by am11** [comment] 2018-03-13 23:49
If you try to increase it to 1 MB, `ulimit -n 1048576`, does it still throw the same exception?

Clang version:

```
/ # clang -v
Alpine clang version 5.0.1 (tags/RELEASE_501/final) (based on LLVM 5.0.1)
Target: x86_64-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by lodi-g** [comment] 2018-03-14 01:25
My hard limit for fds is 4096 and I can't seem to raise it, maybe I'm doing it wrong.

Still, I've tried with 4096 and it didn't work either (infinite loop).

**Comment by Snaipe** [comment] 2018-04-30 17:41
Could you perhaps provide a core file and both executables as compiled by clang and GCC to reproduce this? I'm pretty surprised to see such a weird behaviour.

Out of curiosity, is libcriterion.so compiled with GCC?

**Comment by lodi-g** [comment] 2018-05-16 22:36
Criterion is compiled with GCC.

[GCC compiled binary](https://lodig.me/criterion/gcc.out)
[Clang compiled binary](https://lodig.me/criterion/clang.out)
[Core](https://lodig.me/criterion/core)

Thank you

**Comment by Snaipe** [comment] 2018-05-17 06:59
I don't think I saw which version of Criterion you were using. Are you using a release, or just compiling from bleeding?

The core file seems to be empty btw, but I've had a quick look at the generated binaries, and it looks like I should be able to debug what's happening.

**Comment by Snaipe** [comment] 2018-05-17 09:08
I can reproduce it.

It turns out that it's way worse than just being stuck in an infinite loop; Criterion is fork-bombing itself until the process limit is reached, or the OS gets DoS'ed. I suspect that when compiled with clang, Criterion can't find the address of `main`, or it does, but it's not the right one (perhaps the address of the PLT stub...)

**Comment by Snaipe** [comment] 2018-05-17 10:35
My hunch was right.

In the child process, the patched address is `0x55e205fb4000`, which looks like the base address of our PIE; however, our main is not defined in the PIE, but in libcriterion.so. Case in point, the real address looks like `0x7feb579967d0`.

My tests were done with a very simple setup with BoxFort, essentially an empty file named `empty.c`, compiled with clang, and a simple library called `libmain` compiled with GCC, that just spawns a worker. When compiling with gcc, BoxFort picks up the right address, but with clang, the resolution gives back the address of the PLT stub.

I'm still looking into why this happens, but I noticed that just letting the linker resolve the symbol will give back the right address, so I think I'll just nuke the search code for `main` in BoxFort and just use `return (void *)main;`

**Comment by Snaipe** [comment] 2018-05-17 12:10
I'm escalating the issue, since fork-bombing the host system just because you switched compilers is extremely bad.

**Comment by kyechou** [comment] 2018-10-11 07:31
The issue can also be reproduced with Clang 7.0.0 on Arch Linux `4.18.12-arch1-1-ARCH`.

**Comment by kugel-** [comment] 2018-10-24 06:13
@Snaipe Is there any progress on this?

**Comment by Snaipe** [comment] 2018-10-24 15:08
I have a fix in the works on BoxFort, but I got a bit short on time to clean it up and make sure something like this doesn't happen in the future.

**Comment by Snaipe** [comment] 2018-10-30 21:49
I have pushed a fix on the `fix/247` branch. @lodi-g @kyechou @kugel- can you test it out and confirm if you're still affected?

I'll release 2.3.3 once I'm sure the issue is fixed.

**Comment by kyechou** [comment] 2018-10-31 04:44
I've just tested it out and it works just fine with both gcc and clang on most cases, but I noticed 2 strange behaviors when compiling with clang.

1. When ThreadSanitizer is enabled (compiling and linking with `-fsanitize=thread`), Criterion reported the following error and exited abnormally. The tests are run in a 4-core virtual machine with 10G memory and the error doesn't appear without the ThreadSanitizer flag. I'm not really sure if it's a criterion issue or a clang issue. The same program runs correctly with the same flag used with gcc on the same machine.

```
$ LD_LIBRARY_PATH=. ./test
criterion: Could not initialize inheritable arena: Resource temporarily unavailable
```

2. When a program is compiled and linked with `--coverage` flag, it runs correctly, but takes a lot longer (about 30 sec more).
![screenshot from 2018-10-30 21-40-16](https://user-images.githubusercontent.com/11006026/47765949-6a391400-dc9a-11e8-9ab5-48be8cf2508b.png) The same program runs and exits within a second with gcc.

However, these two minor issues don't seem to be related to the current issue. Perhaps I should open new issues if you feel like they're related to criterion. :)

**Comment by dramforever** [comment] 2018-11-01 10:02
This also affects GCC 7.3.0 for me. Although there doesn't seem to be a fork-bomb, the test binary, when run, just outputs this one line and goes `abort`.

```
criterion: Could not spawn test instance: Protocol error
```

**Comment by Snaipe** [comment] 2018-11-01 16:01
I think that error actually shares the same root-cause (broken dynsym search code in BoxFort) but ended up having different effects due to how gcc and clang generate the symbol tables. In the case of clang, the address of the dynamic symbol ended up being a valid PLT address, while in your case it was some other non-executable address, crashing the test worker when it tried jumping to it. I'm guessing maybe a GOT pointer?

In any case, the BoxFort quick fix addressed both issues.

**Comment by Snaipe** [comment] 2018-11-02 12:13
No need to; it will get automatically closed when I'll push the tagged release.

**Comment by Snaipe** [comment] 2018-11-02 12:16
@kyechou I'd be grateful if you opened a new issue about your problems with ThreadSanitizer. I'm also not sure if the --coverage slowdown is normal, because I'd expect coverage instrumentation to add quite a bit of code, but I would be interested in getting some profiling info in a separate issue.

**Comment by kyechou** [comment] 2018-11-02 14:07
@Snaipe Sure, I'd like to do more tests on the 2.3.3 release regarding those potential issues.

**Comment by Snaipe** [comment] 2018-11-02 15:22
Can you instead try those on `bleeding`? I don't plan to have a 2.3.4 after that, and bleeding reflects the to-be 2.4.0.

**Comment by Snaipe** [comment] 2018-11-05 00:56
v2.3.3 has been released.

**Closed by Snaipe** 2018-11-05 00:56 UTC
Labels: Bug, Linux, Major, Runtime
