### ISSUE TITLE
New tag/release

### ISSUE THREAD

**Issue by hydrapolic** [Snaipe/Criterion#336] opened 2020-01-09 22:21 UTC
Would you mind creating a new tag so we can create a new Gentoo Linux package for it? The current one seems 100 commits behind.

Thanks

**Comment by Snaipe** [comment] 2020-01-09 23:25
Thanks for looking at this. The next scheduled release is 2.4.0, and I'm not 100% happy with the stability of the new assertion API right now. The good news is that I'm actively working to get a first release candidate out since the Debian folks are also interested in packaging Criterion.

**Comment by hydrapolic** [comment] 2020-01-09 23:45
Cool, thanks.

**Comment by kugel-** [comment] 2020-01-10 06:51
Is there some sort of compatibility or will upgrading suddenly break all our 1000s of tests?

**Comment by hydrapolic** [comment] 2020-01-10 07:58
I've tried building the latest snapshot and all tests for syslog-ng passed fine.

**Comment by Snaipe** [comment] 2020-01-10 14:41
There's no reason why everything would break, but the problem is that I haven't validated that all of the "legacy" assertions are still all working. I want to add back in a test for all of these first and get a passing build.

**Comment by madebr** [comment] 2020-11-03 18:28
The last criterion release (2.3.3) is still using cmake.
I would like to create a recipe for [conan-center-index](https://conan.io/center/).
I'll wait with this until a release with meson support is done to avoid doing throw-away work.

**Comment by hydrapolic** [comment] 2021-05-07 13:08
Ping :)

**Comment by Snaipe** [comment] 2022-01-01 14:18
We're working on getting v2.4.0 out; ironing out the last few issues with some outstanding help :)

Closing this in favor of #401.

**Closed by Snaipe** 2022-01-01 14:18 UTC
