### ISSUE TITLE
Memory Leak ？

### ISSUE THREAD

**Issue by BruceChen7** [Snaipe/Criterion#25] opened 2015-05-05 13:54 UTC
When I do noting in the unit test,it seems to have memory leak problem? For example:

```
#include <criterion/criterion.h>
Test(Hello,Hello)
{

}
```
![desctop screenshot](https://cloud.githubusercontent.com/assets/4377940/7473972/3677205a-f371-11e4-9762-0fcff7f90444.png)

Please confirm the problem!!!

**Comment by Snaipe** [comment] 2015-05-05 14:12
Duplicate of #21 
Each worker runs in a separate process, and exit() early to release all the memory to the kernel at once.
If you want to run valgrind on your tests, use `--no-early-exit`.

**Closed by Snaipe** 2015-05-05 14:12 UTC
